#----------------------------------------------------------------
# Travis-CI configuration for R packages
#
# REFERENCES:
# * Travis CI: https://docs.travis-ci.com/user/languages/r
# * covr: https://github.com/jimhester/covr
#
# Validate your .travis.yml file at https://lint.travis-ci.org/
#----------------------------------------------------------------
language: r
sudo: false
cache: packages
warnings_are_errors: false
r_check_args: --as-cran
latex: false

r_packages:
  - future.BatchJobs
  - future.batchtools

bioc_packages:
  - Biobase
  - BiocParallel

matrix:
  include:
    - os: linux
      r: oldrel
      r_packages:
        - future.BatchJobs
        - future.batchtools
    - os: linux
      r: release
      r_packages:
        - future.BatchJobs
        - future.batchtools
      r_github_packages:
        - jimhester/covr
        - jimhester/lintr
      after_success:
        - Rscript -e 'covr::codecov(quiet = FALSE)'
        - Rscript -e 'library(lintr); lint_package(linters = with_defaults(commented_code_linter = NULL, closed_curly_linter = closed_curly_linter(allow_single_line = TRUE), open_curly_linter = open_curly_linter(allow_single_line = TRUE)))'
      env: NB='w/ covr & lintr' ## Just a label
    - os: linux
      r: devel
      r_packages:
        - future.BatchJobs
        - future.batchtools
    - os: osx
      r: oldrel
      r_packages:
        - future.BatchJobs
        - future.batchtools
    - os: osx
      r: release
      r_packages:
        - future.BatchJobs
        - future.batchtools
    - os: linux
      r: release
      r_packages:
        - future.BatchJobs
        - future.batchtools
      r_check_args: --no-build-vignettes --no-codoc --no-examples --no-tests --no-manual --ignore-vignettes
      env:
        - NB='w/ foreach' ## Just a label
        - _R_CHECK_TESTSETS_=foreach
        - _R_CHECK_FUTURE_STRATEGIES_=sequential,multicore,multisession,batchjobs_local,batchtools_local
      after_success:
        - R CMD INSTALL --no-docs doFuture_*.tar.gz
        - Rscript -e 'source("tests/zzz_opt-in,foreach.R", chdir = TRUE, echo = TRUE)'
    - os: linux
      r: release
      r_packages:
        - future.BatchJobs
        - future.batchtools
        - caret
        - class
        - foreign
        - lattice
        - MASS
        - Matrix
        - nlme
        - nnet
        - rpart
        - survival
        - BradleyTerry2
        - e1071
        - earth
        - fastICA
        - gam
        - ipred
        - kernlab
        - klaR
        - ellipse
        - mda
        - mgcv
        - mlbench
        - MLmetrics
        - party
        - pls
        - pROC
        - proxy
        - randomForest
        - RANN
        - spls
        - subselect
        - pamr
        - superpc
        - Cubist
        - pls
        - recipes
      r_check_args: --no-build-vignettes --no-codoc --no-examples --no-tests --no-manual --ignore-vignettes
      env:
        - NB='w/ caret' ## Just a label
        - _R_CHECK_TESTSETS_=caret
        - _R_CHECK_FUTURE_STRATEGIES_=sequential,multicore,multisession,batchjobs_local,batchtools_local
      after_success:
        - R CMD INSTALL --no-docs doFuture_*.tar.gz
        - Rscript -e 'source("tests/zzz_opt-in,caret.R", chdir = TRUE, echo = TRUE)'
    - os: linux
      r: release
      r_packages:
        - future.BatchJobs
        - future.batchtools
        - NMF
        - cluster
        - lattice
        - MASS
      r_check_args: --no-build-vignettes --no-codoc --no-examples --no-tests --no-manual --ignore-vignettes
      env:
        - NB='w/ NMF' ## Just a label
        - _R_CHECK_TESTSETS_=NMF
        - _R_CHECK_FUTURE_STRATEGIES_=sequential,multicore,multisession,batchjobs_local,batchtools_local
      after_success:
        - R CMD INSTALL --no-docs doFuture_*.tar.gz
        - Rscript -e 'source("tests/zzz_opt-in,NMF.R", chdir = TRUE, echo = TRUE)'
    - os: linux
      r: release
      r_packages:
        - future.BatchJobs
        - future.batchtools
        - TSP
        - cluster
        - foreign
        - lattice
        - MASS
        - maps
        - sp
        - maptools
      r_check_args: --no-build-vignettes --no-codoc --no-examples --no-tests --no-manual --ignore-vignettes
      env:
        - NB='w/ TSP' ## Just a label
        - _R_CHECK_TESTSETS_=TSP
        - _R_CHECK_FUTURE_STRATEGIES_=sequential,multicore,multisession,batchjobs_local,batchtools_local
      after_success:
        - R CMD INSTALL --no-docs doFuture_*.tar.gz
        - Rscript -e 'source("tests/zzz_opt-in,TSP.R", chdir = TRUE, echo = TRUE)'
    - os: linux
      r: release
      r_packages:
        - future.BatchJobs
        - future.batchtools
        - glmnet
        - cluster
        - lattice
        - MASS
        - Matrix
        - survival
        - lars
      r_check_args: --no-build-vignettes --no-codoc --no-examples --no-tests --no-manual --ignore-vignettes
      env:
        - NB='w/ glmnet' ## Just a label
        - _R_CHECK_TESTSETS_=glmnet
        - _R_CHECK_FUTURE_STRATEGIES_=sequential,multicore,multisession,batchjobs_local,batchtools_local
      after_success:
        - R CMD INSTALL --no-docs doFuture_*.tar.gz
        - Rscript -e 'source("tests/zzz_opt-in,glmnet.R", chdir = TRUE, echo = TRUE)'
    - os: linux
      r: release
      r_packages:
        - future.BatchJobs
        - future.batchtools
        - plyr
      r_check_args: --no-build-vignettes --no-codoc --no-examples --no-tests --no-manual --ignore-vignettes
      env:
        - NB='w/ plyr & sequential' ## Just a label
        - _R_CHECK_TESTSETS_=plyr
        - _R_CHECK_FUTURE_STRATEGIES_=sequential
      after_success:
        - R CMD INSTALL --no-docs doFuture_*.tar.gz
        - Rscript -e 'source("tests/zzz_opt-in,plyr.R", chdir = TRUE, echo = TRUE)'
    - os: linux
      r: release
      r_packages:
        - future.BatchJobs
        - future.batchtools
        - plyr
      r_check_args: --no-build-vignettes --no-codoc --no-examples --no-tests --no-manual --ignore-vignettes
      env:
        - NB='w/ plyr & multisession' ## Just a label
        - _R_CHECK_TESTSETS_=plyr
        - _R_CHECK_FUTURE_STRATEGIES_=multisession
      after_success:
        - R CMD INSTALL --no-docs doFuture_*.tar.gz
        - Rscript -e 'source("tests/zzz_opt-in,plyr.R", chdir = TRUE, echo = TRUE)'
    - os: linux
      r: release
      r_packages:
        - future.BatchJobs
        - future.batchtools
        - plyr
      r_check_args: --no-build-vignettes --no-codoc --no-examples --no-tests --no-manual --ignore-vignettes
      env:
        - NB='w/ plyr & future.BatchJobs' ## Just a label
        - _R_CHECK_TESTSETS_=plyr
        - _R_CHECK_FUTURE_STRATEGIES_=batchjobs_local
      after_success:
        - R CMD INSTALL --no-docs doFuture_*.tar.gz
        - Rscript -e 'source("tests/zzz_opt-in,plyr.R", chdir = TRUE, echo = TRUE)'
    - os: linux
      r: release
      r_packages:
        - future.BatchJobs
        - future.batchtools
        - plyr
      r_check_args: --no-build-vignettes --no-codoc --no-examples --no-tests --no-manual --ignore-vignettes
      env:
        - NB='w/ plyr & future.batchtools' ## Just a label
        - _R_CHECK_TESTSETS_=plyr
        - _R_CHECK_FUTURE_STRATEGIES_=batchtools_local
      after_success:
        - R CMD INSTALL --no-docs doFuture_*.tar.gz
        - Rscript -e 'source("tests/zzz_opt-in,plyr.R", chdir = TRUE, echo = TRUE)'

before_install:
  - Rscript -e 'c(physical = parallel::detectCores(logical = FALSE), logical = parallel::detectCores())'
  - export _R_CHECK_TIMINGS_=0

notifications:
  email:
    on_success: change
    on_failure: change
