#----------------------------------------------------------------
# Travis-CI configuration for R packages
#
# REFERENCES:
# * Travis CI: https://docs.travis-ci.com/user/languages/r
# * covr: https://github.com/jimhester/covr
#
# Validate your .travis.yml file at http://lint.travis-ci.org/
#----------------------------------------------------------------
language: r
sudo: false
cache: packages
warnings_are_errors: false
r_check_args: --as-cran
latex: false

r_packages:
  - caret
  - plyr
  - future.BatchJobs
  - future.batchtools
  
bioc_packages:
  - BiocParallel

matrix:
  include:
    - os: linux
      r: oldrel
      r_github_packages:
        - HenrikBengtsson/globals
    - os: linux
      r: release
      r_github_packages:
        - jimhester/covr
        - jimhester/lintr
      after_success:
        - Rscript -e 'covr::codecov(quiet = FALSE)'
        - Rscript -e 'library(lintr); lint_package(linters = with_defaults(commented_code_linter = NULL, closed_curly_linter = closed_curly_linter(allow_single_line = TRUE), open_curly_linter = open_curly_linter(allow_single_line = TRUE)))'
      env: NB='w/ covr & lintr' ## Just a label
    - os: linux
      r: release
      env:
        - NB='w/ foreach' ## Just a label
        - _R_TESTSETS_=foreach
        - _R_CHECK_FUTURE_STRATEGIES_=sequential,multicore,multisession,batchjobs_local,batchtools_local
    - os: linux
      r: release
      r_check_args:
      env:
        - NB='w/ caret' ## Just a label
        - _R_TESTSETS_=caret
        - _R_CHECK_FUTURE_STRATEGIES_=sequential,multicore,multisession,batchjobs_local,batchtools_local
    - os: linux
      r: release
      r_check_args:
      env:
        - NB='w/ NMF' ## Just a label
        - _R_TESTSETS_=NMF
        - _R_CHECK_FUTURE_STRATEGIES_=sequential,multicore,multisession,batchjobs_local,batchtools_local
    - os: linux
      r: release
      r_check_args:
      env:
        - NB='w/ TSP' ## Just a label
        - _R_TESTSETS_=RSP
        - _R_CHECK_FUTURE_STRATEGIES_=sequential,multicore,multisession,batchjobs_local,batchtools_local
    - os: linux
      r: release
      r_check_args:
      env:
        - NB='w/ glmnet' ## Just a label
        - _R_TESTSETS_=glmnet
        - _R_CHECK_FUTURE_STRATEGIES_=sequential,multicore,multisession,batchjobs_local,batchtools_local
    - os: linux
      r: release
      r_check_args:
      env:
        - NB='w/ plyr & parallel' ## Just a label
        - _R_TESTSETS_=plyr
    - os: linux
      r: release
      r_check_args:
      r_packages: future.BatchJobs
      env:
        - NB='w/ plyr & future.BatchJobs' ## Just a label
        - _R_TESTSETS_=plyr
        - _R_CHECK_FUTURE_STRATEGIES_=batchjobs_local
    - os: linux
      r: release
      r_check_args:
      r_github_packages:
        - HenrikBengtsson/future.batchtools
      env:
        - NB='w/ plyr & future.batchtools' ## Just a label
        - _R_TESTSETS_=plyr
        - _R_CHECK_FUTURE_STRATEGIES_=batchtools_local
    - os: linux
      r: devel
      r_github_packages:
        - HenrikBengtsson/globals
    - os: osx
      r: oldrel
      r_github_packages:
        - HenrikBengtsson/globals
    - os: osx
      r: release

before_install:
  - Rscript -e 'c(physical = parallel::detectCores(logical = FALSE), logical = parallel::detectCores())'
  - export _R_CHECK_TIMINGS_=0

notifications:
  email:
    on_success: change
    on_failure: change
