#----------------------------------------------------------------
# Travis-CI configuration for R packages
#
# REFERENCES:
# * Travis CI: https://docs.travis-ci.com/user/languages/r
# * covr: https://github.com/jimhester/covr
#
# Validate your .travis.yml file at http://lint.travis-ci.org/
#----------------------------------------------------------------
language: r
sudo: false
cache: packages

os:
  - linux
  - osx

r:
  - oldrel
  - release
  - devel

matrix:
  exclude:
    - os: osx
      r: devel

bioc_packages:
  - BiocParallel
  
_github_packages:
  - jimhester/covr
  - HenrikBengtsson/future.BatchJobs@develop

before_install:
  - R -e "install.packages('future', type='source')"
  - R -e "install.packages('plyr')"
  - R -e "install.packages('covr')"

after_success:
  - Rscript -e 'covr::codecov(quiet=FALSE)'

notifications:
  email:
    on_success: change
    on_failure: change

