#----------------------------------------------------------------
# Travis-CI configuration for R packages
#
# REFERENCES:
# * Travis CI: https://docs.travis-ci.com/user/languages/r
# * covr: https://github.com/jimhester/covr
#
# Validate your .travis.yml file at http://lint.travis-ci.org/
#----------------------------------------------------------------
language: r
sudo: false
cache: packages
warnings_are_errors: false
r_check_args: --as-cran
latex: false

r_packages:
  - plyr
  - future.BatchJobs
  
bioc_packages:
  - BiocParallel

r_github_packages:
  - HenrikBengtsson/future.batchtools@develop

matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
      r_github_packages:
        - jimhester/covr
      after_success:
        - Rscript -e 'covr::codecov(quiet=FALSE)'
      env:
        - NB='w/ covr'  ## Just a label
    - os: linux
      r: devel
    - os: osx
      r: oldrel
    - os: osx
      r: release

before_install:
  - Rscript -e 'c(physical = parallel::detectCores(logical = FALSE), logical = parallel::detectCores())'

notifications:
  email:
    on_success: change
    on_failure: change
